### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [mciantyre/teensy4-rs-template#5]
```
cargo generate --git https://github.com/mciantyre/teensy4-rs-template --name hello-world
cd .\hello-world\
cargo build --release
[...]
error[E0433]: failed to resolve: could not find `interrupt` in `rt`
  --> C:\Users\X\.cargo\git\checkouts\teensy4-rs-32cd33027d5b365b\ca100f3\src\usb.rs:89:14
   |
89 | #[crate::rt::interrupt]
   |              ^^^^^^^^^ could not find `interrupt` in `rt`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `teensy4-bsp`.

To learn more, run the command again with --verbose.
```

Presumably caused by https://github.com/mciantyre/teensy4-rs/commit/c062ff26eca247f7f78c5b69be455d7656a04aca

**Comment by mciantyre** [comment]
Thanks for the heads up!

This was introduced by mciantyre/teensy4-rs#63. Fixing it now.

If you'd like to work around it, add the following to the `hello-world'`s `Cargo.toml`:

```
[patch.crates-io.cortex-m-rt]
git = "https://github.com/mciantyre/teensy4-rs"
branch = "master"
```

Or, generate the template from the `fix/patch-cortex-m-rt` branch:
```
cargo generate --git https://github.com/mciantyre/teensy4-rs-template --name hello-world --branch fix/patch-cortex-m-rt
```

(Note: that branch will disappear once this is on `master`.)
